list: $/shohabbos/click/models/transaction/columns.yaml
modelClass: Shohabbos\Click\Models\Transaction
title: Transactions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
